name: Build and Push Docker Image for webssh server

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    if: "contains(github.event.head_commit.message, 'docker')"
    runs-on: ubuntu-latest

    steps:
    
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.3.0
    
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Build and push webssh
        uses: docker/build-push-action@v4
        with:
          context: ./src
          push: true
          tags: pablo06/webssh:latest, pablo06/webssh:latest
